const API='https://api.upstox.com/v3';
const token=()=>process.env.UPSTOX_ANALYTICS_TOKEN||'';
const UNIVERSE=['RELIANCE','HDFCBANK','ICICIBANK','SBIN','INFY','TCS','LT','AXISBANK','BHARTIARTL','ITC','SUNPHARMA','MARUTI','M&M','TATASTEEL','ONGC','NTPC','ADANIENT','BAJFINANCE','HINDUNILVR','WIPRO','KOTAKBANK','HCLTECH','POWERGRID','COALINDIA','TATAMOTORS','TITAN','ASIANPAINT','ULTRACEMCO','NESTLEIND','TECHM','TRENT','BEL','HAL','INDUSINDBK','JSWSTEEL','GRASIM','CIPLA','DRREDDY','EICHERMOT','APOLLOHOSP'];
async function get(url){const r=await fetch(url,{headers:{Authorization:`Bearer ${token()}`,Accept:'application/json'},cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j?.errors?.[0]?.message||j?.error||`HTTP ${r.status}`);return j}
async function resolve(symbol){const j=await get('https://api.upstox.com/v2/instruments/search?query='+encodeURIComponent(symbol)+'&exchanges=NSE&segments=EQ&records=30');const x=(j.data||[]).find(a=>a.segment==='NSE_EQ'&&String(a.trading_symbol).toUpperCase()===symbol);if(!x)throw Error(`Instrument not found: ${symbol}`);return x}
function daysAgo(n){const d=new Date();d.setDate(d.getDate()-n);return d.toISOString().slice(0,10)}
async function candles(key,unit,intv,days){const to=new Date().toISOString().slice(0,10);const from=daysAgo(days);const j=await get(`${API}/historical-candle/${encodeURIComponent(key)}/${unit}/${intv}/${to}/${from}`);return (j.data?.candles||[]).map(x=>({ts:x[0],o:+x[1],h:+x[2],l:+x[3],c:+x[4],v:+x[5]||0})).sort((a,b)=>a.ts.localeCompare(b.ts))}
async function intradayDaily(key){try{const j=await get(`${API}/historical-candle/intraday/${encodeURIComponent(key)}/days/1`);return (j.data?.candles||[]).map(x=>({ts:x[0],o:+x[1],h:+x[2],l:+x[3],c:+x[4],v:+x[5]||0})).sort((a,b)=>a.ts.localeCompare(b.ts)).at(-1)||null}catch(e){return null}}
function mergeLive(daily,live){if(!live)return daily;const day=String(live.ts).slice(0,10);const out=[...daily];const i=out.findIndex(x=>String(x.ts).slice(0,10)===day);if(i>=0)out[i]=live;else out.push(live);return out.sort((a,b)=>a.ts.localeCompare(b.ts))}
function rsiSeries(c,n=14){if(c.length<n+1)return[];const out=Array(c.length).fill(null);let g=0,l=0;for(let i=1;i<=n;i++){const d=c[i].c-c[i-1].c;g+=Math.max(d,0);l+=Math.max(-d,0)}let ag=g/n,al=l/n;out[n]=al===0?100:100-100/(1+ag/al);for(let i=n+1;i<c.length;i++){const d=c[i].c-c[i-1].c;ag=(ag*(n-1)+Math.max(d,0))/n;al=(al*(n-1)+Math.max(-d,0))/n;out[i]=al===0?100:100-100/(1+ag/al)}return out}
function rsi(c,n=14){const s=rsiSeries(c,n);return s.at(-1)}
function bb(c,n=20,m=2){if(c.length<n)return null;const a=c.slice(-n).map(x=>x.c),mid=a.reduce((s,x)=>s+x,0)/n,sd=Math.sqrt(a.reduce((s,x)=>s+(x-mid)**2,0)/n),lo=mid-m*sd,hi=mid+m*sd,last=c.at(-1).c;return{mid,lo,hi,pos:(last-lo)/(hi-lo||1)*100,width:(hi-lo)/(mid||1)*100}}
function adx(c,n=14){if(c.length<2*n+1)return null;let tr=[],pdm=[],mdm=[];for(let i=1;i<c.length;i++){const x=c[i],p=c[i-1],up=x.h-p.h,down=p.l-x.l;tr.push(Math.max(x.h-x.l,Math.abs(x.h-p.c),Math.abs(x.l-p.c)));pdm.push(up>down&&up>0?up:0);mdm.push(down>up&&down>0?down:0)}let atr=tr.slice(0,n).reduce((a,b)=>a+b,0)/n,ap=pdm.slice(0,n).reduce((a,b)=>a+b,0)/n,am=mdm.slice(0,n).reduce((a,b)=>a+b,0)/n,dx=[];for(let i=n;i<tr.length;i++){atr=(atr*(n-1)+tr[i])/n;ap=(ap*(n-1)+pdm[i])/n;am=(am*(n-1)+mdm[i])/n;const pi=100*ap/(atr||1),mi=100*am/(atr||1);dx.push(100*Math.abs(pi-mi)/(pi+mi||1))}return dx.length?dx.slice(-n).reduce((a,b)=>a+b,0)/Math.min(n,dx.length):null}
function candlePattern(c){if(c.length<3)return{bull:false,bear:false,name:'None'};const x=c.at(-1),p=c.at(-2),body=Math.abs(x.c-x.o),range=Math.max(x.h-x.l,1e-9),uw=x.h-Math.max(x.o,x.c),lw=Math.min(x.o,x.c)-x.l,bull=x.c>x.o,bear=x.c<x.o;const bullHammer=bull&&lw>=body*1.2&&lw>uw;const bearStar=bear&&uw>=body*1.2&&uw>lw;const bullEngulf=bull&&p.c<p.o&&x.o<=p.c&&x.c>=p.o;const bearEngulf=bear&&p.c>p.o&&x.o>=p.c&&x.c<=p.o;const pMid=(p.o+p.c)/2;const piercing=p.c<p.o&&bull&&x.c>pMid&&x.c<p.o;const dark=p.c>p.o&&bear&&x.c<pMid&&x.c>p.o;const bullBreak=x.c>p.h;const bearBreak=x.c<p.l;const strongBull=bull&&body/range>=.55;const strongBear=bear&&body/range>=.55;if(bullHammer)return{bull:true,bear:false,name:'Hammer'};if(bullEngulf)return{bull:true,bear:false,name:'Bull Engulfing'};if(piercing)return{bull:true,bear:false,name:'Piercing'};if(bullBreak)return{bull:true,bear:false,name:'Bull Break'};if(strongBull)return{bull:true,bear:false,name:'Strong Bull'};if(bearStar)return{bull:false,bear:true,name:'Shooting Star'};if(bearEngulf)return{bull:false,bear:true,name:'Bear Engulfing'};if(dark)return{bull:false,bear:true,name:'Dark Cloud'};if(bearBreak)return{bull:false,bear:true,name:'Bear Break'};if(strongBear)return{bull:false,bear:true,name:'Strong Bear'};return{bull:false,bear:false,name:'None'}}
function div(c){const r=rsiSeries(c);if(c.length<35)return'None';const start=Math.max(0,c.length-35),lows=[],highs=[];for(let i=start+3;i<c.length-3;i++){const lo=c[i].l,hi=c[i].h;if(lo<=Math.min(c[i-3].l,c[i-2].l,c[i-1].l,c[i+1].l,c[i+2].l,c[i+3].l))lows.push(i);if(hi>=Math.max(c[i-3].h,c[i-2].h,c[i-1].h,c[i+1].h,c[i+2].h,c[i+3].h))highs.push(i)}if(lows.length>=2){const a=lows.at(-2),b=lows.at(-1);if(c[b].l<c[a].l&&r[b]>r[a])return'Bull Div';if(c[b].l>c[a].l&&r[b]<r[a])return'NRD'}if(highs.length>=2){const a=highs.at(-2),b=highs.at(-1);if(c[b].h>c[a].h&&r[b]<r[a])return'Bear Div';if(c[b].h<c[a].h&&r[b]>r[a])return'PRD'}return'None'}
function calc(symbol,company,m,w,d,live){const mr=rsi(m),wr=rsi(w),rs=rsiSeries(d),dr=rs.at(-1),prev=rs.at(-2),B=bb(d),A=adx(d),last=d.at(-1),pat=candlePattern(d);const reg=mr>60&&wr>60?'Bullish':mr<40&&wr<40?'Bearish':'Neutral';const longRsi=dr>=35&&dr<=45&&dr>prev;const shortRsi=dr>=55&&dr<=65&&dr<prev;const bullCore=reg==='Bullish'&&longRsi&&pat.bull;const bearCore=reg==='Bearish'&&shortRsi&&pat.bear;const lows=d.length>12?d.slice(-12,-1).map(x=>x.l):[],highs=d.length>12?d.slice(-12,-1).map(x=>x.h):[];const nearSupport=lows.length>0&&last.c<=Math.min(...lows)*1.015;const nearResistance=highs.length>0&&last.c>=Math.max(...highs)*.985;const squeeze=!!B&&B.width<7;const scoreBase=reg==='Bullish'?(mr>65?30:22)+(wr>65?25:18)+(longRsi?25:0)+(pat.bull?15:0):reg==='Bearish'?(mr<35?30:22)+(wr<35?18:0)+(shortRsi?25:0)+(pat.bear?15:0):0;let score=Math.min(100,scoreBase+(A>=25?5:A>=20?3:0)+(B&&(reg==='Bullish'?B.pos<=40:B.pos>=60)?5:0)+(nearSupport||nearResistance?3:0));const setup=bullCore?'LONG SIGNAL':bearCore?'SHORT SIGNAL':reg!=='Neutral'&&((reg==='Bullish'&&dr>=35&&dr<=50)||(reg==='Bearish'&&dr>=50&&dr<=65))?'Watching':'None';const entry=last.c;const sl=bullCore?last.l:bearCore?last.h:null;const risk=sl!=null?Math.abs(entry-sl):null;const target=sl!=null?(bullCore?Math.max(B?.hi||entry,entry+2*risk):Math.min(B?.lo||entry,entry-2*risk)):null;return{symbol,company,price:last.c,monthlyRsi:mr,weeklyRsi:wr,dailyRsi:dr,prevDailyRsi:prev,regime:reg,adx:A,bbPos:B?.pos,bbWidth:B?.width,squeeze,divergence:div(d),setup,score,entry,sl,target,rr:risk?Math.abs(target-entry)/risk:null,riskPerShare:risk,bullPattern:pat.bull?pat.name:null,bearPattern:pat.bear?pat.name:null,rsiReversal:longRsi||shortRsi,nearSupport,nearResistance,live,updated:last.ts,candles:d.slice(-90).map(x=>({t:x.ts,o:x.o,h:x.h,l:x.l,c:x.c}))}}
module.exports=async(q,res)=>{try{res.setHeader('Cache-Control','no-store');if(!token())return res.status(401).json({error:'UPSTOX_ANALYTICS_TOKEN is not configured'});const u=new URL(q.url,'https://app.local'),action=u.searchParams.get('action')||'status';if(action==='status')return res.status(200).json({connected:true,provider:'Upstox'});if(action==='universe')return res.status(200).json({symbols:UNIVERSE});if(action==='stock'){const symbol=(u.searchParams.get('symbol')||'').toUpperCase();if(!symbol)return res.status(400).json({error:'symbol required'});const x=await resolve(symbol);const[m,w,hist,live]=await Promise.all([candles(x.instrument_key,'months','1',1825),candles(x.instrument_key,'weeks','1',730),candles(x.instrument_key,'days','1',365),intradayDaily(x.instrument_key)]);const d=mergeLive(hist,live);return res.status(200).json(calc(symbol,x.name||symbol,m,w,d,!!live));}if(action==='candles'){const key=u.searchParams.get('key'),unit=u.searchParams.get('unit')||'days',intv=u.searchParams.get('interval')||'1';return res.status(200).json({candles:await candles(key,unit,intv,Math.min(3650,+u.searchParams.get('days')||365))})}return res.status(404).json({error:'Unknown action'})}catch(e){console.error(e);return res.status(500).json({error:e.message||'Server error'})}}
